version: "3"
services:
  api:
    build: .
    environment:
      - MONGOURI=mongodb://mongo/myapp
      - PORT=5000
    ports:
      - 5000:5000
      - 9229:9229
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - build:/app/build
    depends_on:
      - mongo
    command: npm run dev:docker

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo:/data/db

volumes:
  node_modules:
  mongo:
  build:
